ポップアップ画面を作成
saitokazumasa3/tabisketch pull request #185
Opened 2024-12-10 01:32 UTC by BruinJr

## 概要

close #149 

- プラン確定のポップアップ作成
- カバー画像を追加するポップアップ作成

### スクリーンショット

![image](https://github.com/user-attachments/assets/62a345fe-9fda-4444-afe8-d8b57f66a2bb)
![image](https://github.com/user-attachments/assets/8cbd7020-a412-4607-b99d-a85c4c0aa4f5)

2024-12-12 02:15 UTC, ishiki11 commented
こっちも欲しい
![image](https://github.com/user-attachments/assets/a56110cf-56a9-4807-bca6-aea3a2c88fc3)

2024-12-15 06:24 UTC, ishiki11 commented on src/main/resources/templates/fragment/popup.html
> +<html lang="en">
```suggestion
<html lang="ja">
```
一応

2024-12-15 06:24 UTC, ishiki11 commented on src/main/resources/templates/fragment/popup.html
> +                        <h3 class="mb-5 text-xl text-red-600 whitespace-nowrap">本当に削除します？</h3>
```suggestion
                        <h3 class="mb-5 text-xl text-red-600 whitespace-nowrap">本当に削除してよろしいですか？</h3>
```
文言ちょこっと変えてほしい

2024-12-15 06:24 UTC, ishiki11 commented on src/main/resources/static/js/shareToggleButton.js
> +            const response = await fetch(`${this.sendUrl}?is_public=${isPublic}`);
```suggestion
            await fetch(`${this.sendUrl}?is_public=${isPublic}`);
```
response使ってないからこれでもよさそう

2024-12-16 02:20 UTC, BruinJr commented on src/main/resources/templates/fragment/popup.html
> +<html lang="en">
[d5ba7e2](https://github.com/saitokazumasa3/tabisketch/pull/185/commits/d5ba7e24adc16b33c719b82a9387950183eefd18)
修正しました。

2024-12-16 02:20 UTC, BruinJr commented on src/main/resources/templates/fragment/popup.html
> +                        <h3 class="mb-5 text-xl text-red-600 whitespace-nowrap">本当に削除します？</h3>
[d5f59f2](https://github.com/saitokazumasa3/tabisketch/pull/185/commits/d5f59f2b598b204339af1bc5707c299b0aca721d)
修正しました。

2024-12-16 02:23 UTC, t-dounoma requested changes
写真のinputについてなんだけど、目的地設定と編集で呼び出されるやつだから、controllerから値受け取ってすでに写真の情報があればそれを表示してる状態にしてて欲しい。
その時は編集もできる状態にしてて欲しい

2024-12-19 14:42 UTC, t-dounoma commented
jsで画像の判定してるっぽいけど、th:fieldでの表示/非表示の切り替えはできなかった？
th:fieldってやつがcontrollerから値を取得するやつなんだけど、この中にimagesってやつが存在してればそれを表示、なければ非表示みたいにできないかなって思って

2024-12-20 03:16 UTC, t-dounoma approved these changes
ごめん酔ってた
LGTM

2024-12-20 03:16 UTC, merged