belongingscontrollerの作成
saitokazumasa3/tabisketch pull request #56
Opened 2024-11-15 01:13 UTC by imanoari

持ち物一覧のコントローラーです

## 概要

close #45 

- PlanBelongingsControllerを作成しました
- /plan/belongings/:uuidにアクセスしたい
- RequestMappingでURLの指定が完結している事を確認
- GetMappingの()の中が空であることを確認
- ファイルの指定先が正しいかを確認

### スクリーンショット

画面ないので割愛

2024-11-15 01:23 UTC, ishiki11 commented
Assigneesおおくね？

2024-11-15 01:30 UTC, ishiki11 approved these changes

2024-11-15 01:31 UTC, ishiki11 commented
いいと思いますが、一応バックエンドの方に確認してもらってください

2024-11-15 01:33 UTC, ken-250 submitted a review, later dismissed
確認しました。

2024-11-15 03:23 UTC, saitokazumasa requested changes

2024-11-15 03:23 UTC, saitokazumasa commented on src/main/java/com/tabisketch/controller/PlanBelongingsController.java
> +    public String planBelongings(@PathVariable("uuid") String uuid) {
関数名 `get` でOK

2024-11-15 03:24 UTC, saitokazumasa commented
後で uuid の方法調べなおして再度確認します

2024-11-15 03:28 UTC, imanoari commented on src/main/java/com/tabisketch/controller/PlanBelongingsController.java
> +    public String planBelongings(@PathVariable("uuid") String uuid) {
変更しました！
939b77215d6c234bc4c574582959c6beef0ab34d

2024-11-18 01:03 UTC, saitokazumasa commented on src/main/java/com/tabisketch/controller/PlanBelongingsController.java
> +    public String planBelongings(@PathVariable("uuid") String uuid) {
おｋ

2024-11-18 04:00 UTC, saitokazumasa requested changes
テスト、動確、諸々足りないかな

2024-12-13 04:01 UTC, saitokazumasa3 commented
後ほどやるので一旦クローズ。

2024-12-13 04:01 UTC, closed without merging