plandetailcontrollerの作成
saitokazumasa3/tabisketch pull request #58
Opened 2024-11-15 01:50 UTC by imanoari

旅行プラン詳細のコントローラーです

## 概要

close　#46 

- PlanDetailControllerを作成しました
- アクセス先→/plan/detail/{uuid}
- RequestMappingでURLの指定が完結しているか
- GetMappingの中が空であることを確認
- ファイルの指定先は正しいか
- ディレクトリに問題はないか

### スクリーンショット

割愛します

2024-11-18 00:42 UTC, ken-250 requested changes

2024-11-18 00:42 UTC, ken-250 commented on src/main/java/com/tabisketch/controller/PlanDetailController.java
> +    public String detail(@PathVariable("uuid") String uuid ) {
他のControllerと同じで `get` でよさそう

2024-11-18 03:59 UTC, saitokazumasa requested changes
テスト、動確、諸々足りないかな

2024-12-13 04:00 UTC, saitokazumasa3 commented
僕やるのでクローズ。

2024-12-13 04:00 UTC, closed without merging